[package]
name = "telos-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = { git = "https://github.com/zesterer/chumsky", rev = "ed0f695df586e39c93f1df28c52a2438eceddf51", features = ["pratt"] }
clap = { version = "4.5.37", features = ["derive"] }
lasso = "0.7.3"
la-arena = "0.3.1"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version ="0.3.19", features = ["env-filter"] }
telos-common = { path = "../common" }
telos-parser = { path = "../parser" }
either = "1.15.0"
itertools = "0.14.0"
